package seed

import "go-robot/internal/models"

// SampleProducts – список начальных карточек продуктов.
var SampleProducts = []models.Product{
	{
		Title:       "Суши Ассорти",
		Description: "Набор свежих суши с лососем и тунцом",
		Price:       "$10",
		Calories:    250,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/htp3f5d2/000002.webp",
	},
	{
		Title:       "Роллы Филадельфия",
		Description: "Классические роллы с лососем и сливочным сыром",
		Price:       "$20",
		Calories:    400,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/DzNjc45s/000003.webp",
	},
	{
		Title:       "Сашими Лосось",
		Description: "Свежий лосось, нарезанный тонкими ломтиками",
		Price:       "$30",
		Calories:    350,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/TwWkN2Hs/000004.webp",
	},
	{
		Title:       "Салат из морепродуктов",
		Description: "Легкий салат с креветками и мидиями",
		Price:       "$40",
		Calories:    500,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/7Lht7n1w/000005.jpg",
	},
	{
		Title:       "Закуски Японские",
		Description: "Набор традиционных японских закусок",
		Price:       "$50",
		Calories:    600,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/QCGf2L2d/000005.webp",
	},

	// Новые карточки продуктов из дополнительного списка:
	// 1. Новые суши
	{
		Title:       "Новинка суши 1",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/YqryGHD8/0000010.webp",
	},
	{
		Title:       "Новинка суши 2",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/YCjnRxHW/0000011.webp",
	},
	{
		Title:       "Новинка суши 3",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/W1K9HJNf/0000012.webp",
	},

	// 2. Новые роллы
	{
		Title:       "Новинка роллы 1",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/dt5NGxzF/0000013.webp",
	},
	{
		Title:       "Новинка роллы 2",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/C5FJqG7d/0000014.webp",
	},
	{
		Title:       "Новинка роллы 3",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/wv50MfhS/0000015.webp",
	},

	// 3. Новые сашими
	{
		Title:       "Новинка сашими 1",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/G2nXcwsF/0000016.webp",
	},
	{
		Title:       "Новинка сашими 2",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/vT3hL42h/0000017.webp",
	},
	{
		Title:       "Новинка сашими 3",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/sfcTRLfW/0000018.webp",
	},

	// 4. Новые салаты
	{
		Title:       "Новинка салаты 1",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/xTpgXbzT/0000019.webp",
	},
	{
		Title:       "Новинка салаты 2",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/4NyQRNSC/0000020.webp",
	},

	// 5. Новые закуски
	{
		Title:       "Новинка закуски 1",
		Description: "Новая карточка продукта закуски",
		Price:       "$51",
		Calories:    610,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/Ghmq3j95/0000021.webp",
	},
	{
		Title:       "Новинка закуски 2",
		Description: "Новая карточка продукта закуски",
		Price:       "$51",
		Calories:    610,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/Bn8pHQT5/0000022.webp",
	},

	// Дополнительные карточки (распределяем по категориям в циклическом порядке)
	{
		Title:       "Новинка суши 4",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/x1WRRD5w/0000023.webp",
	},
	{
		Title:       "Новинка роллы 4",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/SKCG1TtJ/0000024.webp",
	},
	{
		Title:       "Новинка сашими 4",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/QtDJ2QRS/0000025.webp",
	},
	{
		Title:       "Новинка салаты 3",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/PxMQTLHH/0000026.webp",
	},
	{
		Title:       "Новинка закуски 3",
		Description: "Новая карточка продукта закуски",
		Price:       "$51",
		Calories:    610,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/90FtMWX7/0000027.webp",
	},
	{
		Title:       "Новинка суши 5",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/XqHKBTXD/0000028.webp",
	},
	{
		Title:       "Новинка роллы 5",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/DfBPNb5d/0000029.webp",
	},
	{
		Title:       "Новинка сашими 5",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/4N0bfkDY/0000030.webp",
	},
	{
		Title:       "Новинка салаты 4",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/Njr8LCtp/0000031.webp",
	},
	{
		Title:       "Новинка закуски 4",
		Description: "Новая карточка продукта закуски",
		Price:       "$51",
		Calories:    610,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/gJ481fyk/0000032.webp",
	},
	{
		Title:       "Новинка суши 6",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/fbncd7TZ/0000033.webp",
	},
	{
		Title:       "Новинка роллы 6",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/Zq8rx9CN/0000034.webp",
	},
	{
		Title:       "Новинка сашими 6",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/k47W1nbp/0000035.webp",
	},
	{
		Title:       "Новинка салаты 5",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/wMvLz0F5/0000036.jpg",
	},
	{
		Title:       "Новинка закуски 5",
		Description: "Новая карточка продукта закуски",
		Price:       "$51",
		Calories:    610,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/nVRq2fc3/0000037.webp",
	},
	{
		Title:       "Новинка суши 7",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/0jBmyDHT/0000038.webp",
	},
	{
		Title:       "Новинка роллы 7",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/xTBMrGmH/0000040.webp",
	},
	{
		Title:       "Новинка сашими 7",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/jSNNRW61/0000041.webp",
	},
	{
		Title:       "Новинка салаты 7",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/pdHjr2qL/0000042.webp",
	},
	{
		Title:       "Новинка закуски 7",
		Description: "Новая карточка продукта закуски",
		Price:       "$51",
		Calories:    610,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/g0HZ6fTq/0000043.webp",
	},
	{
		Title:       "Новинка суши 8",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/RFCn1grr/0000044.webp",
	},
	{
		Title:       "Новинка роллы 8",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/vBPx05M4/0000045.webp",
	},
	{
		Title:       "Новинка сашими 8",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/x8cJhqTt/0000047.webp",
	},
	{
		Title:       "Новинка салаты 8",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/nrgjJZXZ/0000048.webp",
	},
	{
		Title:       "Новинка закуски 8",
		Description: "Новая карточка продукта закуски",
		Price:       "$51",
		Calories:    610,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/rw60ZV6N/0000049.webp",
	},
	{
		Title:       "Новинка суши 9",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/3xgyPsY5/0000051.webp",
	},
	{
		Title:       "Новинка роллы 9",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/yNsJBL8J/0000052.webp",
	},
	{
		Title:       "Новинка сашими 9",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/gJ0nLrRm/0000053.webp",
	},
	{
		Title:       "Новинка салаты 9",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/C16dGYHD/0000054.webp",
	},
	{
		Title:       "Новинка закуски 9",
		Description: "Новая карточка продукта закуски",
		Price:       "$51",
		Calories:    610,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/44qmnf3R/0000055.webp",
	},
	{
		Title:       "Новинка суши 10",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/qqhqQYjF/0000056.webp",
	},
	{
		Title:       "Новинка роллы 10",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/X75XCRZG/0000057.webp",
	},
	{
		Title:       "Новинка сашими 10",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/DwK0dxsC/0000058.webp",
	},
	{
		Title:       "Новинка салаты 10",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/br8VRcyy/000006.webp",
	},
	{
		Title:       "Новинка закуски 10",
		Description: "Новая карточка продукта закуски",
		Price:       "$51",
		Calories:    610,
		Category:    "закуски",
		ImageURL:    "https://i.postimg.cc/KY0YbFWV/0000061.webp",
	},
	{
		Title:       "Новинка суши 11",
		Description: "Новая карточка продукта суши",
		Price:       "$11",
		Calories:    260,
		Category:    "суши",
		ImageURL:    "https://i.postimg.cc/TwSYy0fJ/0000062.webp",
	},
	{
		Title:       "Новинка роллы 11",
		Description: "Новая карточка продукта роллы",
		Price:       "$21",
		Calories:    410,
		Category:    "роллы",
		ImageURL:    "https://i.postimg.cc/yxPQQQxF/000007.webp",
	},
	{
		Title:       "Новинка сашими 11",
		Description: "Новая карточка продукта сашими",
		Price:       "$31",
		Calories:    360,
		Category:    "сашими",
		ImageURL:    "https://i.postimg.cc/Px1FZrkV/000008.webp",
	},
	{
		Title:       "Новинка салаты 11",
		Description: "Новая карточка продукта салаты",
		Price:       "$41",
		Calories:    510,
		Category:    "салаты",
		ImageURL:    "https://i.postimg.cc/tRtM4TkY/000009.webp",
	},
}



